# Generated by Django 2.2.5 on 2019-09-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdapp', '0002_auto_20190907_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码+MD5加密'),
        ),
    ]
